services:
  # PostgreSQL для сервиса пациентов
  postgres_db:
    image: postgres:15
    container_name: patient_db_postgres_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data