name: "📖 Documentation"
description: "Обновление или исправление документации"
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: what-to-change
    attributes:
      label: "Какое изменение нужно внести?"
      description: "Опишите, что нужно обновить или исправить."
