server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/patient_db
    username: medadmin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop

logging:
  level:
    root: info
    sql: trace